name: wine-10.10-custom-exp-2404 CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: bootstraps-2404.yml
          workflow_conclusion: success
          path: /opt
      - name: Build Wine
        run: |
          sudo apt update
          sudo apt install debootstrap perl git wget xz-utils bubblewrap autoconf
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
          sudo tar -C /opt -xpf /opt/Bootstraps-2404/bootstraps.tar.xz
          chmod +x build_wine-10.10-custom-exp-2404.sh
          export WINE_VERSION="10.10"
          export EXPERIMENTAL_WOW64="true"
          WINE_BRANCH=vanilla ./build_wine-10.10-custom-exp-2404.sh
          sha256sum *.tar.xz
      - uses: actions/upload-artifact@v4
        with:
          name: wine-10.10-custom-exp-2404
          path: ./*.tar.xz
